version: "3"
services:
  frontend:
    build:
      context: .
    container_name: "ui"
    ports:
     - "4200:80"
    networks:
      - apis-for-biogas-project_backend
networks:
  apis-for-biogas-project_backend:
    external: true
