version: "3"
services:
  frontend:
    build:
      context: .
    container_name: "ui"
    ports:
     - "4200:80"
    networks:
      - Remote_backend
networks:
  Remote_backend:
    external: true
